# Dockerfile

# Use the official Python 3.8 image as the base image
FROM python:3.8

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the tclient1.py file from the local directory to the /app directory inside the container
COPY c1.py /app

# Specify the default command to run when the container starts
# In this case, it runs the tclient1.py script using the Python interpreter
CMD ["python3", "c1.py"]