# Dockerfile

# Use the official Python 3.8 image as the base image
FROM python:3.8

# Set the working directory inside the container to /app
WORKDIR /app

# Copy the s1.py file from the local directory to the /app directory inside the container
COPY s1.py /app

# Expose port 8080 on the container
EXPOSE 8080

# Specify the default command to run when the container starts
# In this case, it runs the s1.py script using the Python interpreter
CMD ["python3", "s1.py"]
